<a href="https://colab.research.google.com/github/oisincam/Project-Euler-/blob/main/Project_Euler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project Euler Questions

In [ ]:
#EULER

In [ ]:
import numpy as np 

# Problem 1

In [ ]:
def sumofmult3or5(n):
    total=0
    for i in range(0,n):
        if i%15==0:
            total+=i
        elif i%3==0:
            total+=i
        elif i%5==0:
            total+=i
        else:
            total+=0
    return total
sumofmult3or5(1000)

233168

# Problem 2

In [ ]:
def sumofevenfib(n):
    # First generate the fibonacci numbers
    v=[0]
    a=1
    i=0
    while i<n:
        if a<4000000:
            v=np.append(v,a)
            a=v[i+1]+v[i]
            i+=1
        else:
            
            i+=n
    total=0
    for fib in v:
        if fib%2==0:
            print(fib)
            total+=fib
        else:
            total+=0
            
    return total,v
sumofevenfib(100)

0
2
8
34
144
610
2584
10946
46368
196418
832040
3524578


(4613732,
 array([      0,       1,       1,       2,       3,       5,       8,
             13,      21,      34,      55,      89,     144,     233,
            377,     610,     987,    1597,    2584,    4181,    6765,
          10946,   17711,   28657,   46368,   75025,  121393,  196418,
         317811,  514229,  832040, 1346269, 2178309, 3524578]))

## Problem 3

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [ ]:
np.sqrt(600851475143)

775146.0992245268

In [ ]:
n=600851475143
factors= np.array([])
#we generate an array of primes in problem 7
# for p in primes:
#     if n%p==0:
#         factors=np.append(factors,p)
# factors

NameError: name 'primes' is not defined

# Problem 4

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [ ]:
def NumToArrayFlip(x):
    digits=np.array([])
    
    l=int(np.log10(x))+1
    digit_i= x%10
    digits=np.append(digits,digit_i)
    
    for i in range(1,l):
        digit_i= x %(10**(i+1))
        
        for j in range(0,i):
            digit_i= digit_i-digits[j]*(10**(j))
            
        digit_i=digit_i*(10**(-i))
        digits=np.append(digits,digit_i)
        
    return digits

def FlipArray(array):
    l=len(array)
    flipped=np.zeros(l)
    for i in range(0,l):
        flipped[i]=array[l-1-i]
        
    return flipped
x=123456


In [ ]:
def IsPal(x):
    result = False
    if np.linalg.norm( NumToArrayFlip(x)-FlipArray(NumToArrayFlip(x)) ) <0.5:
        result =True
    return result
IsPal(1234321)


True

In [ ]:

#First, we need to generate a list of products of three digit numbers, from the top down
PalFound=False
i_r=10
j_r=10
product=0
k=0
a=999
b=999
pal=0
for i in range(50,100):
    for j in range(k,k+30):
        product= (a-i)*(b-j)
        if IsPal(product)==True:
            pal=product
            print([a-i,b-j])
            break
print(pal)

[913, 993]
906609


# Problem 6

In [ ]:
def squareddif(n):
    i=0
    total1=0
    while i<=n:
        total1+=i**2
        i+=1
    k=0
    total2=0
    while k<=n:
        total2+=k
        k+=1
    result = total2**2-total1
    return result
squareddif(100)

25164150

# Problem 7

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [ ]:
primes = np.array([2,3,5,7,11])# Initiate some primes
n=13
while len(primes)< 10001:#we want this many primes
    k=0
    for p in primes: # check if e
        if p*p <= n:
            if n%p == 0:
                k+=1
                break
    if k ==0: 
        primes=np.append(primes,n)
        
    n+=2
print(primes)
print(len(primes))
#print(primes[10000])

<ipython-input-6-70ee3c72eb34>:6: RuntimeWarning: overflow encountered in long_scalars
  if p*p <= n:


KeyboardInterrupt: 

In [ ]:
primes

array([    2,     3,     5, ..., 83009, 83023, 83047])

In [ ]:
def GenPrimesA(n):#Ancient Sieve of Eratosthenes
    array = []
    primes=[2]
    
    for i in range(0,n+1): # create an array of numbers up to n
        array=np.append(array, i)
    return array 
GenPrimesA(100)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

In [ ]:
len(primes)
juice=primes[0:10000]
primes[100]

# Problem 8

In [ ]:
def NumToArray(x):
    res = [ int(dig) for dig in str(x)]
    return res
NumToArray(2019)
NumToArray(45)

n = '73167176531330624919225119674426574742355349194934'\
'96983520312774506326239578318016984801869478851843'\
'85861560789112949495459501737958331952853208805511'\
'12540698747158523863050715693290963295227443043557'\
'66896648950445244523161731856403098711121722383113'\
'62229893423380308135336276614282806444486645238749'\
'30358907296290491560440772390713810515859307960866'\
'70172427121883998797908792274921901699720888093776'\
'65727333001053367881220235421809751254540594752243'\
'52584907711670556013604839586446706324415722155397'\
'53697817977846174064955149290862569321978468622482'\
'83972241375657056057490261407972968652414535100474'\
'82166370484403199890008895243450658541227588666881'\
'16427171479924442928230863465674813919123162824586'\
'17866458359124566529476545682848912883142607690042'\
'24219022671055626321111109370544217506941658960408'\
'07198403850962455444362981230987879927244284909188'\
'84580156166097919133875499200524063689912560717606'\
'05886116467109405077541002256983155200055935729725'\
'71636269561882670428252483600823257530420752963450'
a=[int(dig) for dig in n]
a
prods=[]
for i in range(0,1000-13):
    prod=1
    for j in range(0,13):
        prod= prod*a[i+j]
    prods=np.append(prods,prod)
np.max(prods)

23514624000.0

# Problem 9

In [ ]:
for a in range (1,1000):
    b= (-1000000+2000*a)/(2*a -2000)
    c=1000-a-b
    if np.abs(b-np.floor(b))<0.001 and b>0 and c>0:
        print(a*b*c)
        break

31875000.0


# Problem 10

The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [ ]:
max(primes)

6829

# Problem 12 

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

In [ ]:
def DivCount(x): 
    ndiv = 2
    for n in range(2,int(np.ceil(x/2))+1):
        if x%n == 0:
            ndiv+=1
    return ndiv 
DivCount(126)

12

In [ ]:
tri = 1 # the first triangle number
n=2
div500 = False # we have yet to find a triangle numb with 500 divisors
while div500 == False: 
    tri +=n
    if DivCount(tri) > 150:
        print(tri)
        div500 = True
    else: n+=1

749700


# Problem 14

In [ ]:
memo={}
k=0
crown=0
def collatz(n):
    if not n in memo:
        if n==1:
            memo[n]= 1
        elif n%2==0:
            memo[n]=collatz(n/2)+1
        else:
            memo[n]= collatz(3*n+1)+1
    return memo[n]

for i in range(1,1000001):
    collatz(i)
    if memo[i]>k:
        k=memo[i]
        crown=i

print(crown)
print (k) 

837799
525


# Problem 31

In the United Kingdom the currency is made up of pound (£) and pence (p). There are eight coins in general circulation:

1p, 2p, 5p, 10p, 20p, 50p, £1 (100p), and £2 (200p).
It is possible to make £2 in the following way:

1×£1 + 1×50p + 2×20p + 1×5p + 1×2p + 3×1p
How many different ways can £2 be made using any number of coins?

In [ ]:
tot=0
sum=0
for x_1 in range(0,201):
    sum = 0
    sum = 1*x_1
    if sum >200:
        sum += -1*x_1
        
    for x_2 in range(0,101):
        sum += 2*x_2
        if sum >200:
            sum+=-2*x_2
            
        for x_5 in range(0,41):
            sum += 5*x_5
            if sum >200:
                sum+=-5*x_5
                
            for x_10 in range(0,21):
                sum += 10*x_10
                if sum >200:
                    sum+=-10*x_10
                    
                for x_20 in range(0,11):
                    sum += 20*x_20
                    if sum >200:
                        sum+= -20*x_20
                        
                    for x_50 in range(0,4):
                        sum += 50*x_50
                        if sum >200:
                            sum+= -50*x_50
                                             
                        for x_100 in range(0,3):
                            print(x_1,x_2,x_5,x_10,x_20,x_50,x_100)
                            sum += 100*x_100
                            print(sum)
                            if sum >200:
                                sum+= -100*x_100
                                                          
                            if sum == 200:
                                tot+=1
                            
print(tot)

In [ ]:
for i in range(0,3):
    for j in range(0,3):
        for k in range(0,3):

In [ ]:
sum = 0
for x_1 in range(0,3):

# Problem 19 $\checkmark $

In [ ]:
date = np.array([0,0,1901,1]) 
#[date,month,year,day of week] mod x, mod 12, year, mod 7 repectively
thirty = [8,3,5,10]
total = 0

while date[2]<2001:
  if date[0]==0 and date[3]==6:
    total+=1
  #increment the day
  date[3] = (date[3]+1)%7

  #increment date based on what month it is
  #if in special month 
  if bool(date[1] in thirty):
    date[0]= (date[0]+1)%30
  #if in february
  elif date[1] == 1:
      #check for potential leap year
      if date[2]%4==0:
        if date[2]%100==0 and date[2]%400!=0:
          date[0] = (date[0]+1)%28
        elif date[2]%100==0 and date[2]%400==0:
         date[0] = (date[0]+1)%29
        else:
          date[0] = (date[0]+1)%29
      else:  
        date[0] = (date[0]+1)%28
  else:
    date[0] = (date[0]+1)%31

  if date[0]==0:
    date[1]= (date[1]+1)%12

  if date[1]==0 and date[0]==0:
    date[2]+=1 

In [ ]:
total

171